name: Release

on:
  workflow_dispatch:
  pull_request_target:
  push:

env:
  VERSION: "2.9.0"

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
          docker-image: [django, nginx]

    steps:

      - name: Checkout original DefectDojo repo
        uses: actions/checkout@v3
        with:
          repository: 'DefectDojo/django-DefectDojo'
          ref: 'release/${{ env.VERSION }}'
          clean: false

      - name: Check
        run: |
          ls -la

      - name: Checkout base repo
        uses: actions/checkout@v3
        with:
          clean: false
          path: 'base-repo'

      - name: Check
        run: |
          ls -la
          cd 'base-repo'
          ls -la

      - name: Replace some files for defectdojo customization
        run: |
          mv ./base-repo/customization/Dockerfile.django ./
          mv ./base-repo/customization/Dockerfile.nginx ./
          mv ./base-repo/customization/requirements.txt ./
          mv ./base-repo/customization/settings.dist.py ./dojo/settings/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v2
        env:
          REPO_ORG: agiliway
          docker-image: ${{ matrix.docker-image }}
        with:
          push: true
          tags: ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:${{ env.VERSION }}, ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:latest
          file: ./Dockerfile.${{ env.docker-image }}
          context: .